/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 6777b383668af3da333916fe9dd6fd74)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	API: Fetcher /* cfshop-api */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
